name: Daily Commit Automation

on:
  schedule:
    # Runs every day at 05:30 UTC
    - cron: "30 5 * * *"
  workflow_dispatch: # allow manual trigger

jobs:
  daily-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add commit by 23f2001539@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date -u)" > last_run.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_run.txt
          git commit -m "Automated daily update [skip ci]" || echo "No changes to commit"
          git push
